# Memory Configuration for Local Agent Studio
# This file defines settings for Mem0 integration and memory management

# Mem0 Memory System Configuration
memory:
  mem0_enabled: true
  memory_db_path: "data/memory"
  
  # Time-to-Live (TTL) settings for different memory types
  profile_ttl_days: 365      # User profiles persist for 1 year
  facts_ttl_days: 180        # Facts persist for 6 months
  conversation_ttl_days: 30   # Conversation history for 1 month
  
  # Memory size and retention policies
  max_memory_size_mb: 500
  enable_memory_compression: true
  retention_policy: "lru"  # Options: lru, fifo, custom
  
  # Memory retrieval settings
  max_relevant_memories: 10
  similarity_threshold: 0.7
  context_window_size: 5  # Number of related memories to include
  enable_temporal_weighting: true  # Weight recent memories higher